name: Update Page

on:
  schedule:
    - cron: '1 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update page
        run: |
          git add .
          git commit -m "atualização automatica do dia"
          git push
